### ISSUE TITLE
Conversion from Jekyll to Hugo

### ISSUE THREAD

**Issue by ilieghiciuc** [digitalcraftsman/hugo-cactus-theme#8]
Hi,

I am looking for someone to help me with a conversion of a theme "the right way" from Jekyll to Hugo.

Would you be interested in this? Sorry to contact you like this but I couldn't find another channel to contact you on :)

Looking forward to your reply,
IG

**Comment by digitalcraftsman** [comment]
Hello Ilie,

depending on my schedule and the comlexity of your theme I could help. In order to get a better understanding of this project I would like to know
- what would be my role in the conversion (e.g. as advisor)?
- which website/theme do you want to migrate exactly to Hugo?
- how experienced are you with Hugo?

Preferred, we could use [Gitter](https://gitter.im/digitalcraftsman) for further communication, if you like.

Best regards,
Digitalcraftsman
